// @generated by @hexagen/sync — rate-limiting template
// Framework: nitro

export type RateLimitBucket = "text" | "image" | "general";

export interface RateLimitResult {
  allowed: boolean;
  bucket: RateLimitBucket;
  limit: number;
  remaining: number;
  resetAt: number; // Unix timestamp (seconds)
}
