// @generated by @hexagen/sync — rate-limiting template
import type { RateLimitResult } from "../../types/rate-limit.js";

export interface RateLimitExceededBody {
  error: "rate_limit_exceeded";
  bucket: string;
  limit: number;
  remaining: 0;
  retryAfter: number;
  message: string;
}

export function buildRateLimitExceededBody(
  result: RateLimitResult,
): RateLimitExceededBody {
  const retryAfter = Math.max(
    0,
    result.resetAt - Math.floor(Date.now() / 1000),
  );
  return {
    error: "rate_limit_exceeded",
    bucket: result.bucket,
    limit: result.limit,
    remaining: 0,
    retryAfter,
    message: `Too many ${result.bucket} requests. Try again in ${retryAfter} seconds.`,
  };
}

export function rateLimitHeaders(
  result: RateLimitResult,
): Record<string, string> {
  const retryAfter = Math.max(
    0,
    result.resetAt - Math.floor(Date.now() / 1000),
  );
  return {
    "X-RateLimit-Limit": String(result.limit),
    "X-RateLimit-Remaining": String(result.remaining),
    "X-RateLimit-Reset": String(result.resetAt),
    "Retry-After": String(retryAfter),
  };
}
