// @generated by @hexagen/sync — rate-limiting template
// Framework: nitro
//
// This middleware is written for Nitro (h3). For other frameworks:
//   nextjs-api  — wrap in a Next.js middleware.ts using NextRequest/NextResponse
//   express     — export (req, res, next) => {} using req.headers and res.setHeader
//   fastify     — register as a preHandler hook using request.headers and reply.header
import {
  defineEventHandler,
  getCookie,
  setCookie,
  createError,
  getRequestURL,
} from "h3";
import { checkRateLimit } from "../utils/rate-limiter.js";
import { getClientIp } from "../utils/get-client-ip.js";
import { getOrCreateSessionId } from "../utils/session-id.js";
import {
  buildRateLimitExceededBody,
  rateLimitHeaders,
} from "../errors/rate-limit-exceeded.error.js";
import type { RateLimitBucket } from "../../types/rate-limit.js";

const DIFFERENTIATED = true;

// Add or reorder entries to customise bucket routing.
// The first matching rule wins; unmatched requests fall through to "general".
const BUCKET_ROUTES: Array<{
  method: string;
  pattern: RegExp;
  bucket: RateLimitBucket;
}> = [
  { method: "POST", pattern: /^\/api\/generate\/text/, bucket: "text" },
  { method: "POST", pattern: /^\/api\/generate\/image/, bucket: "image" },
];

function resolveBucket(method: string, pathname: string): RateLimitBucket {
  if (!DIFFERENTIATED) return "general";
  for (const route of BUCKET_ROUTES) {
    if (route.method === method && route.pattern.test(pathname)) {
      return route.bucket;
    }
  }
  return "general";
}

export default defineEventHandler((event) => {
  const req = event.node.req;
  const res = event.node.res;

  const ip = getClientIp(
    req.headers as Record<string, string | string[] | undefined>,
    req.socket?.remoteAddress,
  );

  // Use session cookie as primary identifier; fall back to IP for cookieless clients
  const clientId =
    getOrCreateSessionId(
      (name) => getCookie(event, name),
      (name, value, opts) => setCookie(event, name, value, opts),
    ) || ip;

  const method = (req.method ?? "GET").toUpperCase();
  const pathname = getRequestURL(event).pathname;
  const bucket = resolveBucket(method, pathname);
  const result = checkRateLimit(clientId, bucket);

  const headers = rateLimitHeaders(result);
  for (const [name, value] of Object.entries(headers)) {
    res.setHeader(name, value);
  }

  if (!result.allowed) {
    throw createError({
      statusCode: 429,
      data: buildRateLimitExceededBody(result),
    });
  }
});
