// @generated by @hexagen/sync — rate-limiting template

// Set RATE_LIMIT_TRUST_PROXY=true only when a trusted reverse proxy (e.g. Nginx,
// Cloudflare, AWS ALB) unconditionally overwrites X-Forwarded-For. In direct-to-app
// or untrusted-proxy deployments leave it false (the default) — otherwise clients
// can spoof the header to rotate identities and bypass IP-based rate limiting.
const TRUST_PROXY = process.env.RATE_LIMIT_TRUST_PROXY === "true";

export function getClientIp(
  headers: Record<string, string | string[] | undefined>,
  remoteAddress?: string,
): string {
  const socketAddr = (remoteAddress ?? "unknown").replace(/^::ffff:/, "");

  if (TRUST_PROXY) {
    const forwarded = headers["x-forwarded-for"];
    if (forwarded) {
      const raw = Array.isArray(forwarded) ? forwarded[0] : forwarded;
      return raw
        .split(",")[0]
        .trim()
        .replace(/^::ffff:/, "");
    }
  }

  return socketAddr;
}
