// @generated by @hexagen/sync — rate-limiting template
// Redis-backed: false
// When true, replace the in-memory store with an ioredis INCR+EXPIREAT implementation
// and add REDIS_URL to your .env.local.
import type {
  RateLimitBucket,
  RateLimitResult,
} from "../../types/rate-limit.js";

const WINDOW_MS = 60_000;

interface WindowEntry {
  count: number;
  resetAt: number; // Unix seconds
}

const store = new Map<string, WindowEntry>();

const LIMITS: Record<RateLimitBucket, number> = {
  text: Number(process.env.TEXT_RPM ?? 40),
  image: Number(process.env.IMAGE_RPM ?? 12),
  general: Number(process.env.GENERAL_RPM ?? 60),
};

const WARN_AT = Number(process.env.RATE_LIMIT_WARN_AT ?? 0.8);
const DEBUG = process.env.RATE_LIMIT_DEBUG === "true";

export function checkRateLimit(
  clientId: string,
  bucket: RateLimitBucket,
): RateLimitResult {
  const key = `${clientId}:${bucket}`;
  const now = Date.now();
  const resetAt = Math.ceil((now + WINDOW_MS) / 1000);
  const limit = LIMITS[bucket];

  let entry = store.get(key);
  if (!entry || now >= entry.resetAt * 1000) {
    entry = { count: 0, resetAt };
    store.set(key, entry);
  }

  entry.count += 1;
  const remaining = Math.max(0, limit - entry.count);
  const allowed = entry.count <= limit;

  if (DEBUG) {
    const pct = entry.count / limit;
    if (!allowed) {
      // eslint-disable-next-line no-console -- DEBUG-gated rate-limit diagnostic
      console.log(
        `[rate-limit:block] clientId=${clientId} bucket=${bucket} limit=${limit} resetAt=${entry.resetAt}`,
      );
    } else if (pct >= WARN_AT) {
      // eslint-disable-next-line no-console -- DEBUG-gated rate-limit diagnostic
      console.log(
        `[rate-limit:warn] clientId=${clientId} bucket=${bucket} at ${entry.count}/${limit} (${Math.round(pct * 100)}%)`,
      );
    } else {
      // eslint-disable-next-line no-console -- DEBUG-gated rate-limit diagnostic
      console.log(
        `[rate-limit] clientId=${clientId} bucket=${bucket} remaining=${remaining}/${limit}`,
      );
    }
  }

  return { allowed, bucket, limit, remaining, resetAt: entry.resetAt };
}

// Purge expired entries to prevent unbounded memory growth
if (typeof setInterval !== "undefined") {
  const cleanupInterval = setInterval(() => {
    const now = Date.now();
    for (const [key, entry] of store) {
      if (now >= entry.resetAt * 1000) store.delete(key);
    }
  }, WINDOW_MS);
  // unref() is not available in all runtimes (e.g. edge, serverless)
  if (typeof (cleanupInterval as { unref?: unknown }).unref === "function") {
    (cleanupInterval as NodeJS.Timeout).unref();
  }
}
