// @generated by @hexagen/sync — rate-limiting template
import crypto from "node:crypto";

const COOKIE_NAME = "__session";
const SESSION_TTL = Number(process.env.RATE_LIMIT_SESSION_TTL ?? 604_800);
const IS_PROD = process.env.NODE_ENV === "production";

export function getOrCreateSessionId(
  getCookie: (name: string) => string | undefined,
  setCookie: (
    name: string,
    value: string,
    options: Record<string, unknown>,
  ) => void,
): string {
  const existing = getCookie(COOKIE_NAME);
  if (existing) return existing;

  const id = crypto.randomUUID();
  setCookie(COOKIE_NAME, id, {
    httpOnly: true,
    sameSite: "lax",
    secure: IS_PROD,
    maxAge: SESSION_TTL,
    path: "/",
  });
  return id;
}
